[features]
seeds = false
skip-lint = false

[programs.mainnet]
triad_protocol = "TRDwq3BN4mP3m9KsuNUWSN6QDff93VKGSwE95Jbr9Ss"

[provider]
cluster = "mainnet"
wallet = "/Users/dannpl/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
